[package]

name = "markov"
version = "0.0.33"
description = "A generic markov chain implementation in Rust."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "CC0-1.0"
keywords = ["markov", "chain", "probability"]
documentation = "https://docs.rs/markov/0.0.33/markov/"
repository = "https://github.com/aatxe/markov"
readme = "README.md"

[dependencies]
getopts = { version = "0.2", optional = true }
rand = "0.3"
petgraph = "0.4"
itertools = "0.7"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
skeptic = "0.10.0"

[dev-dependencies]
skeptic = "0.10.0"
